# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(602, 429)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list_users = QtWidgets.QListWidget(self.centralwidget)
        self.list_users.setGeometry(QtCore.QRect(40, 60, 241, 211))
        self.list_users.setStyleSheet("background-color: rgba(255,255,255,100);border: 1px solid #1565C0;border-radius: 8px;")
        self.list_users.setObjectName("list_users")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.select_user = QtWidgets.QPushButton(self.centralwidget)
        self.select_user.setGeometry(QtCore.QRect(40, 280, 115, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.select_user.setFont(font)
        self.select_user.setStyleSheet("background-color: rgba(255,255,255,100);border: 1px solid #1565C0;border-radius: 8px;")
        self.select_user.setObjectName("select_user")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 20, 211, 31))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(330, 60, 211, 31))
        self.name.setStyleSheet("background-color: rgba(255,255,255,100);border: 1px solid #1565C0;border-radius: 8px;")
        self.name.setObjectName("name")
        self.add_user = QtWidgets.QPushButton(self.centralwidget)
        self.add_user.setGeometry(QtCore.QRect(330, 100, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_user.setFont(font)
        self.add_user.setStyleSheet("background-color: rgba(255,255,255,100);border: 1px solid #1565C0;border-radius: 8px;")
        self.add_user.setObjectName("add_user")
        self.delete_user = QtWidgets.QPushButton(self.centralwidget)
        self.delete_user.setGeometry(QtCore.QRect(160, 280, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.delete_user.setFont(font)
        self.delete_user.setStyleSheet("background-color: rgba(255,255,255,100);border: 1px solid #1565C0;border-radius: 8px;")
        self.delete_user.setObjectName("delete_user")
        self.statistics = QtWidgets.QPushButton(self.centralwidget)
        self.statistics.setGeometry(QtCore.QRect(40, 316, 240, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.statistics.setFont(font)
        self.statistics.setStyleSheet("background-color: rgba(255,255,255,100);border: 1px solid #1565C0;border-radius: 8px;")
        self.statistics.setObjectName("statistics")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 602, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Авторизация"))
        self.label.setText(_translate("MainWindow", "Выберите свой аккаунт:"))
        self.select_user.setText(_translate("MainWindow", "Выбрать"))
        self.label_2.setText(_translate("MainWindow", "Создать новый"))
        self.add_user.setText(_translate("MainWindow", "Создать"))
        self.delete_user.setText(_translate("MainWindow", "Удалить"))
        self.statistics.setText(_translate("MainWindow", "Посмотреть статистику"))
